package main

import (
	"hf-api/src/internal/app/api"
	"log"
	"os"
	"path/filepath"
)

func main() {
	if len(os.Args) < 2 {
		log.Fatalf("output file required")
	}

	outputFile := os.Args[1]

	if outputFile == "--" {
		outputFile = os.Args[2]
	}

	if _, err := filepath.Abs(outputFile); err != nil {
		log.Fatalf("malformed path: %v", err)
	}

	allTokenAliases := map[string]string{}

	for k, v := range api.KnownTokens {
		for _, alias := range v {
			allTokenAliases[alias] = k
		}
	}

	file, err := os.OpenFile(outputFile, os.O_WRONLY|os.O_CREATE, 0644)

	if err != nil {
		log.Fatalf("failed to open file for write: %v", err)
	}

	defer file.Close()

	file.WriteString("// Code generated by codegens/codegens.go; DO NOT EDIT.\n\n")
	file.WriteString("package api\n\n")
	file.WriteString("var TokenAliasMap = map[string]string{\n")
	for alias, token := range allTokenAliases {
		file.WriteString("\t\"" + alias + "\": \"" + token + "\",\n")
	}
	file.WriteString("}\n")
}
